CXX = g++
CXXFLAGS = -std=c++17

a : a.cc
	$(CXX) $(CXXFLAGS) $< -I ../library -o $@

b : b.cc
	$(CXX) $(CXXFLAGS) $< -I ../library -o $@

c : c.cc
	$(CXX) $(CXXFLAGS) $< -I ../library -o $@

d : d.cc
	$(CXX) $(CXXFLAGS) $< -I ../library -o $@

e : e.cc
	$(CXX) $(CXXFLAGS) $< -I ../library -o $@

f : f.cc
	$(CXX) $(CXXFLAGS) $< -I ../library -o $@
